### ISSUE TITLE
how to use tensorRT accelerate controlNet

### ISSUE THREAD

**Issue by VitoChenLY** [hnsywangxin/controlnet_stable_tensorrt#10]
So controlNet in the project does not use tensorRT to accelerate it? If you want to use tensorRT to accelerate controlNet, how can you do it?

**Comment by hnsywangxin** [comment]
> So controlNet in the project does not use tensorRT to accelerate it? If you want to use tensorRT to accelerate controlNet, how can you do it?

I used tensorRT to accelerate controlnet with stable diffusion, you can refer other repo, this repo is old and I have no time to update
