### ISSUE TITLE
关于显存占用

### ISSUE THREAD

**Issue by lucasjinreal** [hnsywangxin/controlnet_stable_tensorrt#4]
楼主说用了30GB现存，对此我感到十分震惊，真的有这么恐怖吗？

**Comment by hnsywangxin** [comment]
> 楼主说用了30GB现存，对此我感到十分震惊，真的有这么恐怖吗？

这个是nvidia官方的bug，这个可以在issue里面找到，理论上只要不到10G的显存就可以了的

**Comment by lucasjinreal** [comment]
@hnsywangxin 是生成的时候要这么多显存，还是跑的时候要这么多显存啊

**Comment by hnsywangxin** [comment]
> @hnsywangxin 是生成的时候要这么多显存，还是跑的时候要这么多显存啊

推理
