### ISSUE TITLE
SDXL + ipadapter+contorlnet 

### ISSUE THREAD

**Issue by xxddccaa** [hnsywangxin/controlnet_stable_tensorrt#9]
SDXL + ipadapter+contorlnet 的加速，个人贡献￥1000赞助开发

**Comment by hnsywangxin** [comment]
> SDXL + ipadapter+contorlnet 的加速，个人贡献￥1000赞助开发

哈哈，感谢信任，目前工作繁忙，暂时没有时间来维护这个repo
